title: Daniel Groneberg
logo: /portfolio_assets/img/danicon2.jpg
description: Data Scientist With Background in Earth Science
#show_downloads: true
theme: jekyll-theme-minimal
source: ./
assets_dir: portfolio_assets
custom_links:
  linkedin: https://www.linkedin.com/
  resume: nitrome.com

