title: Daniel Groneberg
logo: /portfolio_assets/img/danicon2.jpg
description: Data Scientist With a Background in Earth Science
show_downloads: true
theme: jekyll-theme-minimal
source: ./
#assets_dir: portfolio_assets/img/
